### ISSUE TITLE
[Linux] (System.PlattformNotSupportedException) (8013159h)

### ISSUE THREAD

**Issue by OfficialLambdax** [Unknown6656/AutoIt-Interpreter#186]
### Bug description
```
$ dotnet autoit3.dll --help
[System.PlatformNotSupportedException] (80131539h) Operation is not supported on this platform.:
   at System.ConsolePal.get_CursorVisible()
   at System.Console.get_CursorVisible()
   at Unknown6656.Controls.Console.ConsoleExtensions.SaveConsoleState()
   at Unknown6656.AutoIt3.CLI.MainProgram.Start(String[] argv)
   at Program.<Main>$(String[] args)
```

### Steps to reproduce
1. Install Manjaro Linux, dotnet-runtime and sdk for version 8 of .NET
2. download latest pre release of Autoit-Interpreter
3. run `dotnet autoit3.dll --help`

### Used system
 - OS: Manjaro Linux
 - Architecture: Intel
 - Interpreter Version: [Beta] Version 0.9.2146.8608
 - Core Library Version: _The version can be found using the command `autoit --version`_ - no idea
 - Commit hash: f8e3fdf
[additional configuration information]

### Additional context
This error is displayed through ssh and on monitor

**Comment by Unknown6656** [comment]
@OfficialLambdax sorry for responding this late. Thanks for bringing the issue to my attention. I will try to resolve it asap.

**Comment by Unknown6656** [comment]
Hopefully fixed with 7bd3ec5a84be79f7d01ac36e3ba9e14f7f338ec6:

![image](https://github.com/Unknown6656/AutoIt-Interpreter/assets/8807985/cc7475af-8420-41d6-9fe0-e368f6170534)

**Comment by OfficialLambdax** [comment]
I will try this out as soon as the next release comes out, thank you alot for looking into it!

**Comment by Unknown6656** [comment]
I pushed a new release: https://github.com/Unknown6656/AutoIt-Interpreter/releases/tag/0.10.2166.8633

Let me know if you still encounter this issue.

**Comment by OfficialLambdax** [comment]
Yes this seems to have fixed it, i can now successfully execute the `dotnet autoit3.dll --help` command. I will be doing tests with it, thank you again! 👍

**Comment by Unknown6656** [comment]
sure thing, you're welcome. Sorry for the long wait.
